# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/dilsizk/Desktop/ece491/ece491labs/Lab05/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/dilsizk/Desktop/ece491/ece491labs/Lab05/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
read_verilog -library xil_defaultlib -sv {
  C:/Users/dilsizk/Desktop/ece491/ece491labs/Lab05/project_1/project_1.srcs/sources_1/new/correlator.sv
  C:/Users/dilsizk/Desktop/ece491/ece491labs/Lab05/project_1/project_1.srcs/sources_1/new/seven_seg.sv
  C:/Users/dilsizk/Desktop/ece491/ece491labs/Lab05/mux8_parm.sv
  C:/Users/dilsizk/Desktop/ece491/ece491labs/Lab05/decoder_3_8_en.sv
  C:/Users/dilsizk/Desktop/ece491/ece491labs/Lab05/counter_parm.sv
  C:/Users/dilsizk/Desktop/ece491/ece491labs/Lab05/project_1/project_1.srcs/sources_1/new/clkenb.sv
  C:/Users/dilsizk/Desktop/ece491/ece491labs/Lab05/project_1/project_1.srcs/sources_1/new/s_fifo4_modified.sv
  C:/Users/dilsizk/Desktop/ece491/ece491labs/Lab05/Buffer/m_transmitter.sv
  C:/Users/dilsizk/Desktop/ece491/ece491labs/Lab05/mxtest_2.sv
  C:/Users/dilsizk/Desktop/ece491/ece491labs/Lab05/project_1/project_1.srcs/sources_1/new/dispctl.sv
  C:/Users/dilsizk/Desktop/ece491/ece491labs/Lab05/Buffer/async_tran.sv
  C:/Users/dilsizk/Desktop/ece491/ece491labs/Lab05/project_1/project_1.srcs/sources_1/new/mx_rcvr.sv
  C:/Users/dilsizk/Desktop/ece491/ece491labs/Lab05/project_1/project_1.srcs/sources_1/new/topmodule.sv
  C:/Users/dilsizk/Desktop/ece491/ece491labs/Lab05/project_1/project_1.srcs/sources_1/new/nexys4DDR.sv
  C:/Users/dilsizk/Desktop/ece491/ece491labs/Lab05/debounce.sv
  C:/Users/dilsizk/Desktop/ece491/ece491labs/Lab05/Buffer/fifo_4.sv
  C:/Users/dilsizk/Desktop/ece491/ece491labs/Lab05/project_1/project_1.srcs/sources_1/new/check_p.sv
  C:/Users/dilsizk/Desktop/ece491/ece491labs/Lab05/project_1/project_1.srcs/sources_1/new/decoder_rxd.sv
  C:/Users/dilsizk/Desktop/ece491/ece491labs/Lab05/Buffer/check_p.sv
  C:/Users/dilsizk/Desktop/ece491/ece491labs/Lab05/project_1/project_1.srcs/sources_1/new/register.sv
  C:/Users/dilsizk/Desktop/ece491/ece491labs/Lab05/project_1/project_1.srcs/sources_1/new/mx_rcvr2.sv
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/dilsizk/Desktop/ece491/ece491labs/Lab05/project_1/project_1.srcs/constrs_1/new/nexys4DDR.xdc
set_property used_in_implementation false [get_files C:/Users/dilsizk/Desktop/ece491/ece491labs/Lab05/project_1/project_1.srcs/constrs_1/new/nexys4DDR.xdc]


synth_design -top topmodule -part xc7a100tcsg324-1


write_checkpoint -force -noxdef topmodule.dcp

catch { report_utilization -file topmodule_utilization_synth.rpt -pb topmodule_utilization_synth.pb }
