# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/dilsizk/Desktop/ece491final/ece491labs/Project/FinalProjectTransmitter/FinalProjectTransmitter/FinalProjectTransmitter.cache/wt [current_project]
set_property parent.project_path C:/Users/dilsizk/Desktop/ece491final/ece491labs/Project/FinalProjectTransmitter/FinalProjectTransmitter/FinalProjectTransmitter.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
read_verilog -library xil_defaultlib -sv {
  C:/Users/dilsizk/Desktop/ece491final/ece491labs/Project/FinalProjectTransmitter/FinalProjectTransmitter/clkenb.sv
  C:/Users/dilsizk/Desktop/ece491final/ece491labs/Project/FinalProjectTransmitter/FinalProjectTransmitter/extras/single_pulser.sv
  C:/Users/dilsizk/Desktop/ece491final/ece491labs/Project/FinalProjectTransmitter/FinalProjectTransmitter/FinalProjectTransmitter.srcs/sources_1/new/p_fifo4.sv
  C:/Users/dilsizk/Desktop/ece491final/ece491labs/Project/FinalProjectTransmitter/FinalProjectTransmitter/FinalProjectTransmitter.srcs/sources_1/new/aync_rcvr.sv
  C:/Users/dilsizk/Desktop/ece491final/ece491labs/Project/FinalProjectTransmitter/FinalProjectTransmitter/FinalProjectTransmitter.srcs/sources_1/new/m_transmitter.sv
  C:/Users/dilsizk/Desktop/ece491final/ece491labs/Project/FinalProjectTransmitter/FinalProjectTransmitter/FinalProjectTransmitter.srcs/sources_1/new/trans_controller_2.sv
  C:/Users/dilsizk/Desktop/ece491final/ece491labs/Project/FinalProject/topmodulefinal.sv
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/dilsizk/Desktop/ece491final/ece491labs/Project/FinalProject/nexys4DDR.xdc
set_property used_in_implementation false [get_files C:/Users/dilsizk/Desktop/ece491final/ece491labs/Project/FinalProject/nexys4DDR.xdc]


synth_design -top topmodulefinal -part xc7a100tcsg324-1


write_checkpoint -force -noxdef topmodulefinal.dcp

catch { report_utilization -file topmodulefinal_utilization_synth.rpt -pb topmodulefinal_utilization_synth.pb }
