webtalk_init -webtalk_dir C:/Users/dilsizk/Desktop/ece491final/ece491labs/Project/FinalProjectTransmitter/FinalProjectTransmitter/FinalProjectTransmitter.sim/sim_1/behav/xsim.dir/trans_control_test_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Dec 08 08:32:44 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2016.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1577090" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "87b18fd44573504dbf7b2e3226a3c4c1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "627d14ec3a3a48048835e83db00dd158" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "25" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E3-1271 v3 @ 3.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3591 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key SystemVerilog -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key File_Counter -value "8" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "175 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "7 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "230" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "75" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "15" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "0.31_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "44320_KB" -context "xsim\\usage"
webtalk_transmit -clientid 247084344 -regid "" -xml C:/Users/dilsizk/Desktop/ece491final/ece491labs/Project/FinalProjectTransmitter/FinalProjectTransmitter/FinalProjectTransmitter.sim/sim_1/behav/xsim.dir/trans_control_test_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/dilsizk/Desktop/ece491final/ece491labs/Project/FinalProjectTransmitter/FinalProjectTransmitter/FinalProjectTransmitter.sim/sim_1/behav/xsim.dir/trans_control_test_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/dilsizk/Desktop/ece491final/ece491labs/Project/FinalProjectTransmitter/FinalProjectTransmitter/FinalProjectTransmitter.sim/sim_1/behav/xsim.dir/trans_control_test_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
